---
title: "Cleaning 2016_2022 Enroll Dataset"
output: html_document
---

```{r}
library('tidyverse')
```

```{r}
df1 = read.csv("2016_2020_enroll.csv")
df1 = subset(df1, select = -c(1,3,5,6,20,22,24,26,28,30,32:36,38:39))
```

```{r}
removal = numeric(0)
for(i in 1:nrow(df1)){
  if(grepl("%", df1$X..Poverty[i], fixed=TRUE)){
    removal = append(removal,i)
  }
}
df1 = df1[-removal,]
df1$X..Poverty = as.integer(df1$X..Poverty)
```

```{r}
df2 = aggregate(. ~ School.Name, df1, sum)
cbind(lapply(lapply(df2, is.na),sum))
```

```{r}
elem = mid = high = numeric(nrow(df2))
for(i in 1:nrow(df2)){
  if(df2$Grade.1[i]!=0 & df2$Grade.2[i]!=0 & df2$Grade.3[i]!=0 & df2$Grade.4[i]!=0 & df2$Grade.5[i]!=0){
    elem[i]=1
  }
  if(df2$Grade.6[i]!=0 & df2$Grade.7[i]!=0 & df2$Grade.8[i]!=0){
    mid[i]=1
  }
  if(df2$Grade.9[i]!=0 & df2$Grade.10[i]!=0 & df2$Grade.11[i]!=0 & df2$Grade.12[i]!=0){
    high[i]=1
  }
}

df2$elem = elem
df2$mid = mid
df2$high = high
df2$School.Name = rownames(df2)
```

```{r}
df3 = df2[,c(1,2,15,16,23,24,25,3:14,17:22)]
write.csv(df3, "cleaned_2016_2020_enroll.csv")
```